plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.login.server'
version = '0.0.1-SNAPSHOT'
description = 'login-server'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {

  // Spring Web & Security
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

  // Validation (DTO 검증)
  implementation 'org.springframework.boot:spring-boot-starter-validation'

  //JWT
  implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
  runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
  runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
  implementation 'org.springframework.boot:spring-boot-configuration-processor'

  // Persistence JPA
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

  // Mail
  implementation 'org.springframework.boot:spring-boot-starter-mail'

  // Database  & Redis
  implementation 'org.springframework.boot:spring-boot-starter-data-redis'
  runtimeOnly 'org.postgresql:postgresql'
  runtimeOnly 'com.h2database:h2'

  // Environment Variables (.env)
  implementation 'io.github.cdimascio:dotenv-java:3.0.0'
  implementation 'me.paulschwarz:spring-dotenv:4.0.0'

  // View Template
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
  implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

  // Jackson JavaTime module to support java.time types like Instant
  implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.19.4'

  // Developer Tools & Lombok
  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'

  // Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

  //Github CICD Health Check
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

tasks.named('test') {
	useJUnitPlatform()
}
